version: '3.7'
services:
  db:
    image: postgres:13.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: websocket_timer
    expose:
      - 5432

  websocket_timer:
    build: .
    environment:
      SECRET_KEY: 1234
      DATABASE_URL: postgresql://postgres:1234@db:5432/websocket_timer
    # volumes:
    #   - .:/opt/websocket_timer
    ports:
      - 8020:5000
    depends_on:
      - db